name: automation

on:
  schedule:
    - cron:  '0 1 * * *'
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  scrape:
    name: scrape website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout data
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: 'repo'
          clean: true
      - name: prep env
        run: |
          sudo apt-get install -y libxml2-utils
          mkdir -p data
          cd repo
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Scrape data
        run:
          - TAGS=($(git tag | sed -Ee 's/v(.*)/\1/g' | sort -u))
          - LAST_TAG=$(git tag | sed -Ee 's/v(.*)/\1/g' | sort -Vru | head -1)
          - VERSIONS=($(xmllint --html --shell <(curl -sSL https://opensource.apple.com/source/xnu/) <<< 'cat .//a[starts-with(@href,"xnu")]/@href' | fgrep href | sed -Ee 's@.*xnu-([^"/]+)[/"].*@\1@g' | sort -u))
          - DIFFERENCE=($(comm -13 <(for X in "${TAGS[@]}"; do echo "${X}"; done)  <(for X in "${VERSIONS[@]}"; do echo "${X}"; done) | sort -V))
          - for ver in "${DIFFERENCE[@]}"; do [ "${LAST_TAG}" = "$(echo -e "${LAST_TAG}\n$ver" | sort -V | head -n1)" ] && curl -o "./data/xnu-${ver}.tgz" "https://opensource.apple.com/tarballs/xnu/xnu-${ver}.tar.gz"; done
      - name: loop and upload
        run: |
          for f in $(ls data/xnu-* | sort -V); do
          mv $f ./
          gunzip xnu-*.tgz
          tar -xf xnu-*.tar
          rm xnu-*.tar
          ver=$(ls -d xnu-* | sed -Ee 's/xnu-(.*)/\1/g' )
          pushd xnu-${ver}
          mv ../repo/.git .
          mv ../repo/.github .
          rm -rf ../repo
          git add .
          git commit -m "Version ${ver}"
          git tag v${ver}
          git push origin
          git push origin --tags
          popd
          mv xnu-${ver} repo
          done
